### ISSUE TITLE
spork broken

### ISSUE THREAD

**Issue by zhengjia** [teampoltergeist/poltergeist#259]
Hi,

I am using poltergeist with Test::Unit and spork. The test run failed with:

```
Error: test_create_site(SitesTest)
  RangeError: 0x00000081f700f4 is not id value
test/test_helper.rb:42:in `block in <class:IntegrationTest>'
```

It seems this commit caused it: https://github.com/jonleighton/poltergeist/commit/98d4a4a8936e8d6b3417f2c057bafaba40874eee. Reverting this commit fixes the issue.

Backtrace:

```
0x00000083d22cf0 is not id value
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:375:in `_id2ref'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:375:in `to_obj'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1410:in `to_obj'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1708:in `to_obj'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:613:in `recv_request'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:908:in `recv_request'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1523:in `init_with_client'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1535:in `setup_message'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1487:in `perform'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
(druby://127.0.0.1:8988) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1074:in `respond_to?'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1548:in `reopen'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1548:in `perform_without_block'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1508:in `perform'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
(druby://127.0.0.1:62840) /Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/client.rb:100:in `redirect_stdout'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/client.rb:39:in `start'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/client.rb:13:in `start'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/driver.rb:42:in `client'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/driver.rb:25:in `browser'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/poltergeist-1.1.0/lib/capybara/poltergeist/driver.rb:89:in `visit'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/capybara-2.0.2/lib/capybara/session.rb:183:in `visit'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/capybara-2.0.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/testing/setup_and_teardown.rb:72:in `block in run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:436:in `_run__3251419944003795596__setup__3479428108914276392__callbacks'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_setup_callbacks'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/activesupport-3.2.11/lib/active_support/testing/setup_and_teardown.rb:70:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/testsuite.rb:117:in `run_test'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/testsuite.rb:53:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunnermediator.rb:65:in `run_suite'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunnermediator.rb:44:in `block in run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunnermediator.rb:100:in `with_listener'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunnermediator.rb:40:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunner.rb:25:in `start'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/autorunner.rb:409:in `block in run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/autorunner.rb:465:in `change_work_directory'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/test-unit-2.5.3/lib/test/unit/autorunner.rb:408:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-testunit-0.0.8/lib/spork/test_framework/test_unit.rb:88:in `run_tests'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/run_strategy/forking.rb:13:in `block in run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/forker.rb:21:in `block in initialize'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/forker.rb:18:in `fork'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/forker.rb:18:in `initialize'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/laptop/.rvm/gems/ruby-1.9.3-p286-perf/gems/spork-1.0.0rc2/lib/spork/server.rb:48:in `run'
/Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1548:in `perform_without_block'
/Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1508:in `perform'
/Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
/Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
/Users/laptop/.rvm/rubies/ruby-1.9.3-p286-perf/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'

```

**Comment by usman-ahmad** [comment]
I am getting this same error on ruby '1.9.2' with spork (0.9.0), rspec (2.11.0), capybara (1.1.2) and shoulda (3.3.0)

### Error Message
    RangeError
    0x003f9d70dc6f20 is not id value
