### ISSUE TITLE
How to passin the extensions and run it with Capybara?

### ISSUE THREAD

**Issue by millisami** [teampoltergeist/poltergeist#297]
Downloaded the file from https://raw.github.com/ariya/phantomjs/master/examples/netsniff.js
and running `phantomjs netsniff.js http://www.google.com`

will output the Har content into STDOUT.

So I'm trying to use this using Capybara and Poltergeist.

```ruby
require 'capybara'
require 'capybara/dsl'
require 'capybara/poltergeist'

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app,
    phantomjs: "/usr/local/bin/phantomjs",
    extensions: ["netsniff.js"]
  )
end

Capybara.configure do |config|
  config.default_driver = :poltergeist
  config.javascript_driver = :poltergeist
  config.run_server = false
  #config.app_host = ENV['APP'] || 'http://localhost:3000'
  config.default_wait_time = 10
end

@session = Capybara::Session.new(:poltergeist)
@session.visit("http://www.google.com")
```

Running this outputs the following errors:

```
Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/browser.rb:197:in `command': One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details). (Capybara::Poltergeist::JavascriptError)

ReferenceError: Can't find variable: require
    at netsniff.js:96
ReferenceError: Can't find variable: require
    at netsniff.js:96
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/browser.rb:179:in `block in extensions='
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/browser.rb:178:in `each'
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/browser.rb:178:in `extensions='
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/driver.rb:27:in `browser'
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/poltergeist-1.1.0/lib/capybara/poltergeist/driver.rb:89:in `visit'
  from /Users/millisami/Code/WebrailsPhantomjs/.bundle/gems/capybara-2.0.3/lib/capybara/session.rb:183:in `visit'
  from crawly.rb:44:in `login!'
  from crawly.rb:57:in `<main>'
```

So looks like it is finding the netsniff.js file and loaded it. But it didn't understand that `require` line.

1. How can I configure Poltergeist or Capybara to recognize that `require` line to work 
2. How to configure it to dump that HAR output into separate file instead of just STDOUT?

**Comment by twalpole** [comment]
Closing due to lack of response
