### ISSUE TITLE
client.rb:50:in `eof?': stream closed (IOError)

### ISSUE THREAD

**Issue by sethcall** [teampoltergeist/poltergeist#385]
Upon updating to 1.4.0, I get this error when running my rspec tests:

```
.../poltergeist-1.4.0/lib/capybara/poltergeist/client.rb:50:in `eof?': stream closed (IOError)
    .../poltergeist-1.4.0/lib/capybara/poltergeist/client.rb:50:in `block in start'
```

This line of code seems relating to proxying logging data?  I think?

from client.rb:

```
def start
      @read_io, @write_io = IO.pipe
      @out_thread = Thread.new {
        while !@read_io.eof? && data = @read_io.readpartial(1024)  # THIS LINE IS BREAKING
          @phantomjs_logger.write(data)
        end
      }

      process_options = {}
      process_options[:pgroup] = true unless Capybara::Poltergeist.windows?

      redirect_stdout do
        @pid = Process.spawn(*command.map(&:to_s), process_options)
        ObjectSpace.define_finalizer(self, self.class.process_killer(@pid) )
      end
    end
```

Not sure what to think yet.

**Comment by chamnap** [comment]
I faced this problem too. I just wonder the README told that I should call `driver.quit`?
