### ISSUE TITLE
Overlapping but not on screenshot

### ISSUE THREAD

**Issue by ghost** [teampoltergeist/poltergeist#506]
```ruby
it 'require accept terms and can download it' do
    user = c :user, terms_agreed_at: nil
    login user
    screenshot_and_open_image
    page.should have_content 'Terms of Use'
    click_on 'Terms of Use'
    page.response_headers['Content-Type'].should == "application/pdf"
end
```

```
Failures:

  1) Users require accept terms and can download it
     Failure/Error: click_on 'Terms of Use'
     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [343, 731.5] failed. Poltergeist detected another element with CSS selector 'html.js.no-flexbox.flexboxlegacy.canvas.canvastext.no-webgl.touch.no-geolocation.postmessage.websqldatabase.no-indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.cssreflections.csstransforms.no-csstransforms3d.csstransitions.fontface.generatedcontent.no-video.no-audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths body.users section#cookie-policy div.inner p' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
     # ./spec/requests/users_spec.rb:24:in `block (2 levels) in <top (required)>'
```

http://i.imgur.com/LFB1COB.png

If I disable cookie-policy template test passes
http://i.imgur.com/aTI9O4e.png

Then I use `trigger(:click)`
```ruby
it 'require accept terms and can download it' do
    user = c :user, terms_agreed_at: nil
    login user
    screenshot_and_open_image
    page.should have_content 'Terms of Use'
    page.find('label[for=user_terms_agreed_at] a').trigger(:click)
    # click_on 'Terms of Use'
    page.response_headers['Content-Type'].should == "application/pdf"
  end
```
Fails with
```
Failures:

  1) Users require accept terms and can download it
     Failure/Error: page.response_headers['Content-Type'].should == "application/pdf"
       expected: "application/pdf"
            got: nil (using ==)
     # ./spec/requests/users_spec.rb:25:in `block (2 levels) in <top (required)>'

Finished in 4.57 seconds
1 example, 1 failure
```

**Comment by HenryYan2012** [comment]
@yaauie Please refer this https://github.com/goodwill/capybara-select2/issues/14

**Comment by twalpole** [comment]
Closing this until the info requested by @yaaule is provided 
* minimal, complete reproduction steps (e.g., remove your application logic & give the minimal HTML/CSS/JavaScript & a failing test case I can run without any knowledge of your application stack)
* expected behaviour
* observed behaviour

If that is provided we can reopen

**Comment by ianaverno** [comment]
![image](https://user-images.githubusercontent.com/5175391/39446987-01886674-4cc9-11e8-8109-4d9860087708.png)
Having the same issue:

Here's a screenshot, that poltergeist provides me with. There's a dropdown with actions, and it cannot scroll to the appropriate position and click it.
