### ISSUE TITLE
Timeout resetting driver

### ISSUE THREAD

**Issue by alexfalkowski** [teampoltergeist/poltergeist#512]
Hi All,

I seem to be getting an issue when resetting the driver

```
Timed out waiting for response to {"name":"reset","args":[]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:83:in `send'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/server.rb:33:in `send'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:270:in `command'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:161:in `reset'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/poltergeist-1.5.1/lib/capybara/poltergeist/driver.rb:151:in `reset!'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/capybara-2.3.0/lib/capybara/session.rb:95:in `reset!'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/capybara-2.3.0/lib/capybara.rb:255:in `block in reset_sessions!'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/capybara-2.3.0/lib/capybara.rb:255:in `each'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/capybara-2.3.0/lib/capybara.rb:255:in `reset_sessions!'
      /var/lib/jenkins/.rvm/gems/ruby-1.9.3-p448@mortice/gems/capybara-2.3.0/lib/capybara/cucumber.rb:8:in `After'
```

This seems to happen even though the feature is not tagged as javascript (it is tagged as selenium)

Once this happens it seems to break every test after this happens.

[EDIT: @yaauie added markdown delimiters]

**Comment by PavelTyk** [comment]
In my case some web pages fail to load if `phantomjs_logger: Logger.new('/dev/null')`. For example http://blog.momtrusted.com
