### ISSUE TITLE
SyntaxError: Parse error

### ISSUE THREAD

**Issue by crazydog115** [teampoltergeist/poltergeist#587]
Recently, various actions inside of tests, such as calls to `click_button` or `visit` result in 

```
One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

SyntaxError: Parse error
```
This happens inconsistently, and sporadically.

Here's the end of a stack trace
```
/home/rof/cache/bundler/ruby/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:323:in `command'
/home/rof/cache/bundler/ruby/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:31:in `visit'
/home/rof/cache/bundler/ruby/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
/home/rof/cache/bundler/ruby/2.1.0/gems/capybara-2.4.1/lib/capybara/session.rb:226:in `visit'
/home/rof/cache/bundler/ruby/2.1.0/gems/capybara-2.4.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
/home/rof/cache/bundler/ruby/2.1.0/gems/spinach-0.8.10/lib/spinach/capybara.rb:35:in `visit'
```

This only occurs on our CI, Codeship, which is running Phantom JS 1.9.8, using Ruby 2.1.4, and version 1.6.0 of this gem.

**Comment by route** [comment]
Well I'd like to help, but this issue sounds clear. It says PhantomJS cannot parse some js code that resulting in this error. It could be probably network issues or something else... Backtrace isn't helpful and says nothing.
