### ISSUE TITLE
Raising Capybara::Poltergeist::ClickFailed even when the click is possible

### ISSUE THREAD

**Issue by sobrinho** [teampoltergeist/poltergeist#60]
Hi @jonleighton,

I'm receiving that error:

```
1) ContributionImprovements create a new contribution_improvement
     Failure/Error: within_tab 'Itens de Custo' do
     Capybara::Poltergeist::ClickFailed:
       Click at co-ordinates [234.5, -247] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to click.
     # ./spec/support/capybara.rb:20:in `click_link'
     # (eval):2:in `click_link'
     # ./spec/support/helpers.rb:87:in `block in within_tab'
     # ./spec/support/helpers.rb:86:in `within_tab'
     # ./spec/requests/contribution_improvements_spec.rb:76:in `block (2 levels) in <top (required)>'

  2) ContributionImprovements update an existent contribution_improvement
     Failure/Error: within_tab 'Itens de Custo' do
     Capybara::Poltergeist::ClickFailed:
       Click at co-ordinates [234.5, -247] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to click.
     # ./spec/support/capybara.rb:20:in `click_link'
     # (eval):2:in `click_link'
     # ./spec/support/helpers.rb:87:in `block in within_tab'
     # ./spec/support/helpers.rb:86:in `within_tab'
     # ./spec/requests/contribution_improvements_spec.rb:194:in `block (2 levels) in <top (required)>'
```

I can't reproduce that issue in isolation but this is a real issue :P

The failing scenario looks like that:

``` ruby
within_tab 'Itens de Custo' do                                                                                                          
  ...
end
```

The helper:

``` ruby
def within_tab(locator)
  within ".ui-tabs" do
    click_link locator

    within ".ui-tabs-panel:not(.ui-tabs-hide)" do
      yield 
    end
  end
end
```

Reducing the complexity:

```
  1) ContributionImprovements update an existent contribution_improvement
     Failure/Error: click_link 'Itens de Custo'
     Capybara::Poltergeist::ClickFailed:
       Click at co-ordinates [234.5, -247] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to click.
     # ./spec/support/capybara.rb:20:in `click_link'
     # (eval):2:in `click_link'
     # ./spec/requests/contribution_improvements_spec.rb:194:in `block (2 levels) in <top (required)>'
```

``` ruby
click_link 'Itens de Custo'
```

I tried a sleep to check for a strange timeout but didn't work:

``` ruby
sleep 10

click_link 'Itens de Custo'
```

But, if I render the page, the scenario magically pass!

``` ruby
page.driver.render('/tmp/file.png')

click_link 'Itens de Custo'
```

It's consistent, all the time I ran these two scenarios, they fail.

All the time I ran with sleep, they also fail.

All the time I ran with `page.driver.render`, they pass.

I guess this is the useful piece of debug:

```
{"name"=>"find", "args"=>[".//a[./@href][(((./@id = 'Itens de Custo' or normalize-space(string(.)) = 'Itens de Custo') or ./@title = 'Itens de Custo') or .//img[./@alt = 'Itens de Custo'])]"]}
{"response"=>{"page_id"=>4, "ids"=>[88]}}
{"name"=>"visible", "args"=>[4, 88]}
{"response"=>true}
{"name"=>"visible", "args"=>[4, 88]}
{"response"=>true}
{"name"=>"click", "args"=>[4, 88]}
{"error"=>{"name"=>"Poltergeist.ClickFailed", "args"=>[nil, {"x"=>234.5, "y"=>-247}]}}
{"name"=>"reset", "args"=>[]}
{"response"=>true}
```

Calling page.render before the click_link:

```
{"name"=>"render", "args"=>["/tmp/file.png", false]}
{"response"=>true}
{"name"=>"find", "args"=>[".//a[./@href][(((./@id = 'Itens de Custo' or normalize-space(string(.)) = 'Itens de Custo') or ./@title = 'Itens de Custo') or .//img[./@alt = 'Itens de Custo'])]"]}
{"response"=>{"page_id"=>4, "ids"=>[91]}}
{"name"=>"visible", "args"=>[4, 91]}
{"response"=>true}
{"name"=>"visible", "args"=>[4, 91]}
{"response"=>true}
{"name"=>"click", "args"=>[4, 91]}
{"response"=>true}
```

Note: seems like the position of link changes after calling render.

What you think?

Do you need some information about my application (I can send in private)?

Note: it works fine on selenium and the rendered image is exactly what I expect to see at this moment.

**Comment by narendra-chandratre** [comment]
Its still failing for me :( Unable to click with success ! Help
