### ISSUE TITLE
ReferenceError: Can't find variable: require - Stripe OAuth2 flow

### ISSUE THREAD

**Issue by airblade** [teampoltergeist/poltergeist#610]
I'm trying to write a test which navigates [Stripe Connect's OAuth2 flow](https://stripe.com/docs/connect/standalone-accounts) but I keep getting this error when Poltergeist clicks my 'Connect with Stripe' button:

```
SyntaxError: Parse error
SyntaxError: Parse error
ReferenceError: Can't find variable: require
ReferenceError: Can't find variable: require
    at https://a.stripecdn.com/manage/assets/oauth_register-fcdee0513209eb301904a6b1acd6ec3c.js:1
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:275:in `command'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:137:in `click'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/node.rb:17:in `command'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/node.rb:108:in `click'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara/node/element.rb:118:in `block in click'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara/node/base.rb:84:in `synchronize'
    /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara/node/element.rb:118:in `click'
```

The problematic javascript, `oauth_register-fcdee0513209eb301904a6b1acd6ec3c.js`, looks like this:

```js
require(["jquery"],function(e){e(function(){var t=window.readConfig("loginurl_json");e("#account_selector").change(function(){var e=window.location.search.split("&");e[0]&&(e[0]=e[0].replace(/^\?/,""));var t=window.location.origin+window.location.pathname,n="?merchant="+this.value;for(var r=0;r<e.length;r++)/^merchant=/.test(e[r])||(n+="&"+e[r]);window.location=t+n}),e("a.logout").click(function(n){n.preventDefault(),e.ajax({url:"/ajax/sessions",type:"DELETE",headers:{"x-stripe-csrf-token":PRELOADED.csrf_token},success:function(){window.location=t}})})})});
```

Can I solve or workaround this problem at the Poltergeist end?

**Comment by NGTOne** [comment]
I'm seeing this problem as well. Works fine in browsers, falls flat on Poltergeist.

**Comment by twalpole** [comment]
You probably want to try this with phantomjs 2+  (2.0.1 if you can build the development version).  The "browser" provided by phantomjs 1.9.8 is really behind current browsers, and the error you're seeing is because some JS isn't getting loaded properly.   - note phantomjs 2.0.0 has issues with file uploads, 2.0.1 has fixed those issues but hasn't actually been released yet.

**Comment by twalpole** [comment]
Closing since this isn't really a poltergeist issue - its a phantomjs limitation
