### ISSUE TITLE
Not following redirect possibly due to options request

### ISSUE THREAD

**Issue by 7h3kk1d** [teampoltergeist/poltergeist#720]
I'm trying to test a ember.js site with rails apis using capybara and poltergeist. It works fine using chrome/selenium but for some reason I get this in the api log and a redirect from auth isn't followed

```ruby
ActionController::RoutingError (No route matches [OPTIONS] "path"):
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.3.4) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
```

There is no options request being made when using chrome. It should be a get request.

Also of note is the request under page.network_traffic the method is ? instead of get or even options.

Any help would be much appreciated!

```ruby
 #<Capybara::Poltergeist::NetworkTraffic::Request:0x007fcb7cfdcdf8
  @data=
   {"headers"=>
     [{"name"=>"Referer", "value"=>"http://localhost:4200/login?token=asdfasdfawer"},
      {"name"=>"User-Agent", "value"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1"},
      {"name"=>"Accept", "value"=>"*/*"}],
    "id"=>76,
     [{"name"=>"Access-Control-Request-Method", "value"=>"GET"},
      {"name"=>"Origin", "value"=>"http://localhost:4200"},
      {"name"=>"Referer", "value"=>"http://localhost:4200/login?token=asdfasdfawer"},
      {"name"=>"User-Agent", "value"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1"},
      {"name"=>"Access-Control-Request-Headers", "value"=>"accept, origin, x-current-user-urn, authorization"},
      {"name"=>"Accept", "value"=>"*/*"},
      {"name"=>"Content-Length", "value"=>"0"}],
    "id"=>74,
    "method"=>"?",
```

**Comment by twalpole** [comment]
What version of poltergeist and phantomjs are you using?

**Comment by 7h3kk1d** [comment]
I just tried using phantomjs 2.1.1 and master. Same issue.

**Comment by twalpole** [comment]
Ok - can you provide a reproducible example that exhibits this behavior?  Without that it's kind of hard to figure out what would be causing it

**Comment by 7h3kk1d** [comment]
I don't have one I can provide right now but I'll try to generate one asap.

**Comment by twalpole** [comment]
Closing due to lack of response
