### ISSUE TITLE
Poltergeist.BrowserError: TypeError: null is not an object (evaluating 'sequence.key')

### ISSUE THREAD

**Issue by radar** [teampoltergeist/poltergeist#746]
I have a repo which should reproduce this issue: https://github.com/radar/twist/tree/my-saas-stripe

If you run these commands, it should do it:

```
bundle install
bundle exec rspec spec/features/accounts/sign_up_spec.rb
```

When I do this, this is what I see:

```
Failure/Error: csc_input.send_keys(424)
Capybara::Poltergeist::BrowserError:
  There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it.

  Poltergeist.BrowserError: TypeError: null is not an object (evaluating 'sequence.key')
    at send_keys (/Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/browser.js:458:21)
    at runCommand (/Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/browser.js:85:36)
    at run (/Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/cmd.js:26:35)
    at runCommand (/Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/main.js:22:25)
    at commandReceived (/Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/connection.js:16:33)
    at /Users/ryanbigg/.gem/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/client/compiled/connection.js:1:64
```

I am running PhantomJS 2.0.1-regression-12506, which was installed with these commands:

```
curl -L https://github.com/skakri/phantomjs/releases/download/2.0.1-regression-12506/osx-x86_64-phantomjs > /usr/local/bin/phantomjs
   chmod 0755 /usr/local/bin/phantomjs
```

**Comment by simi** [comment]
hello @radar 

Can you try to post string instead of number as `send_keys` parameter [here](https://github.com/radar/twist/blob/746a4457ce677424a7b0ac09b26f60d817438302/spec/features/accounts/sign_up_spec.rb#L47)?

I'm not sure if this is actuall issue, but the errors message shuold be better or we can try to type to string before passing that to JS world.

**Comment by simi** [comment]
Probably we should document this better https://github.com/teampoltergeist/poltergeist#sending-keys.

**Comment by radar** [comment]
Oh is that all it was? Damn! Thanks @simi. This appears to be working now.

**Comment by radar** [comment]
I didn't read the docs, so if you improved them at all then it wouldn't have helped. Sorry for not doing that.
