### ISSUE TITLE
Intermittent failure: undefined method '[]' for nil

### ISSUE THREAD

**Issue by marcandre** [teampoltergeist/poltergeist#769]
I'm really sorry for the flimsy bug report; hopefully this will make sense to someone...

Intermittently, basic capybara tests fail with an error raised deep within poltergeist:

    NoMethodError:   undefined method '[]' for nil:NilClass
    ruby/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:63

Looks like `command` can respond `nil`?

    def find(method, selector)
      result = command('find', method, selector)
      result['ids'].map { |id| [result['page_id'], id] }
    end

This is triggered by a basic `page.should have_content 'foo'`. I've seen this error on travis.ci as well as locally.

Full stacktrace:
```
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:63:in `find'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:120:in `find'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:124:in `find_xpath'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/base.rb:108:in `find_xpath'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/queries/selector_query.rb:112:in `block in resolve_for'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/queries/selector_query.rb:108:in `resolve_for'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/finders.rb:35:in `block in find'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/finders.rb:33:in `find'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/document.rb:24:in `text'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/queries/text_query.rb:18:in `resolve_for'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/matchers.rb:524:in `block in assert_text'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/node/matchers.rb:523:in `assert_text'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/capybara-2.7.0/lib/capybara/rspec/matchers.rb:65:in `matches?'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /mnt/home/u1702/bundle/ruby/2.2.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/syntax.rb:45:in `should'
     # ./spec/features/controlpanel/features/video_feature_spec.rb:85:in `block (4 levels) in <top (required)>'
 ```

**Comment by marcandre** [comment]
Nevermind, please ignore. Sorry :blush:
