### ISSUE TITLE
Capybara::Poltergeist::BrowserError: Modal not being closed

### ISSUE THREAD

**Issue by obromios** [teampoltergeist/poltergeist#799]
I have an intermittent error that produces the following output:

    
```
Failure/Error: click_button 'Update'
     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [74, 635.5] failed. Poltergeist detected another element with CSS selector 'html body.home-page.modal-open strong div#modal_new_user.modal.fade.in' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
     # ./spec/features/clubs_spec.rb:61:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Capybara::Poltergeist::BrowserError:
     #   There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it. 
     #   
     #   Poltergeist.MouseEventFailed: click
     #   html body.home-page.modal-open strong div#modal_new_user.modal.fade.in
     #   {"x"=>74, "y"=>635.5}
     #   ./spec/features/clubs_spec.rb:61:in `block (2 levels) in <top (required)>

```
The relevant part of the spec is

```
   click_button 'Close'
    expect(page).to have_css 'span.help-block', text: 'is not a number'
    fill_in 'Distance', with: 989
    select 'hybrid', from: 'Type'
    click_button 'Update'
```

This spec sometimes fails when  I run all the tests at once. I have not seen it fail when the test is run individually.  The ```click_button 'Close``` closes a modal. It looks like when the test fails, the modal is still open.

**Comment by twalpole** [comment]
This is most likely caused by animation of the modal - if possible you should disable all animations in the test environment - which for bootstrap modals (which I think you're using due to the class names) is detailed - http://getbootstrap.com/javascript/#disabling-transitions

**Comment by obromios** [comment]
I am using bootstrap and jquery. Your comment makes sense, and may clear up a few other problems. 

Thank you
