### ISSUE TITLE
Broken rails UJS loading when use arrow functions

### ISSUE THREAD

**Issue by sd-kin** [teampoltergeist/poltergeist#903]
When you have form with `remote: true` and add some js function, which use arrow function (just have it somewhere, no even need to call it) and submit such form in feature test then you get an unknown format error while in browser form works fine. Using standard function instead of arrow do not lead to such behavior.

phantomJS version: 2.1.1
poltergeist version: 1.15.0
system:  Ubuntu 14.04.5 LTS

debug output and stacktrace:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/poltergeist_bug$ rspec spec/features/submit.rb
{"id":"8c523b10-0493-4f9d-a188-034bf1fad9ed","name":"set_debug","args":[true]}
{"command_id":"8c523b10-0493-4f9d-a188-034bf1fad9ed","response":true}
{"id":"8a56cbad-53bc-4428-bed6-f1df09df42be","name":"visit","args":["http://127.0.0.1:33684/"]}
{"command_id":"8a56cbad-53bc-4428-bed6-f1df09df42be","response":{"status":"success"}}
{"id":"af32d7ce-0c14-4ed2-96bb-6178e009b821","name":"find","args":["xpath",".//input[((((./@type = 'submit') or (./@type = 'reset')) or (./@type = 'image')) or (./@type = 'button'))][((./@id = 'Save') or ((./@value = 'Save') or (./@title = 'Save')))] | .//input[(./@type = 'image')][(./@alt = 'Save')] | .//button[(((./@id = 'Save') or ((./@value = 'Save') or (./@title = 'Save'))) or ((normalize-space(string(.)) = 'Save') or .//img[(./@alt = 'Save')]))] | .//input[(./@type = 'image')][(./@alt = 'Save')]"]}
{"command_id":"af32d7ce-0c14-4ed2-96bb-6178e009b821","response":{"page_id":1,"ids":[0]}}
{"id":"5d8110c2-99db-46ec-b411-4d74746b6ebf","name":"visible","args":[1,0]}
{"command_id":"5d8110c2-99db-46ec-b411-4d74746b6ebf","response":true}
{"id":"77eae35b-869f-4676-8b3d-343af33b321d","name":"disabled","args":[1,0]}
{"command_id":"77eae35b-869f-4676-8b3d-343af33b321d","response":false}
{"id":"ef6ac9a2-e386-4bd3-8758-6511ed01aa76","name":"click","args":[1,0]}
{"command_id":"ef6ac9a2-e386-4bd3-8758-6511ed01aa76","response":{"position":{"x":33.5,"y":42.5}}}
{"id":"41b4a5e0-bce7-45a6-b3f7-ca01358e9dc8","name":"find","args":["xpath","/html"]}
{"command_id":"41b4a5e0-bce7-45a6-b3f7-ca01358e9dc8","response":{"page_id":2,"ids":[0]}}
{"id":"f7062392-1d40-4beb-aab0-acaf2271a54b","name":"visible","args":[2,0]}
{"command_id":"f7062392-1d40-4beb-aab0-acaf2271a54b","response":true}
{"id":"9a403d5a-4bc6-4e54-8737-275454fef778","name":"visible_text","args":[2,0]}
{"command_id":"9a403d5a-4bc6-4e54-8737-275454fef778","response":"Internal Server Error\n\nBaseController#create is missing a template for this request format and variant. request.formats: [\"text/html\"] request.variant: []\nWEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at 127.0.0.1:33684"}
{"id":"a178fdd3-20ea-42d6-aaec-f57359098a0e","name":"find","args":["xpath","/html"]}
{"command_id":"a178fdd3-20ea-42d6-aaec-f57359098a0e","response":{"page_id":2,"ids":[1]}}
{"id":"cf860fbe-ecef-46fe-b378-840e43c3ae34","name":"visible","args":[2,1]}
{"command_id":"cf860fbe-ecef-46fe-b378-840e43c3ae34","response":true}
{"id":"47859a23-5e3a-4880-b3b0-32f38319ef81","name":"all_text","args":[2,1]}
{"command_id":"47859a23-5e3a-4880-b3b0-32f38319ef81","response":"Internal Server Error\n  \n    Internal Server Error\n    BaseController#create is missing a template for this request format and variant.\n\nrequest.formats: [\"text/html\"]\nrequest.variant: []\n    \n    \n     WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at\n     127.0.0.1:33684\n    \n  \n\n"}
{"id":"52d65b8b-be30-43f9-b0a0-40896a235e7e","name":"reset","args":[]}
{"command_id":"52d65b8b-be30-43f9-b0a0-40896a235e7e","response":true}
F

Failures:

  1) Submit form via AJAX submit
     Failure/Error: raise ActionController::UnknownFormat, message

     ActionController::UnknownFormat:
       BaseController#create is missing a template for this request format and variant.

       request.formats: ["text/html"]
       request.variant: []
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/engine.rb:522:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/capybara-2.15.1/lib/capybara/server.rb:44:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
     # ------------------
     # --- Caused by: ---
     # Capybara::ExpectationNotMet:
     #   expected to find text "form submitted succesfully" in "Internal Server Error BaseController#create is missing a template for this request format and variant. request.formats: [\"text/html\"] request.variant: [] WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at 127.0.0.1:33684"
     #   /home/vagrant/.rvm/gems/ruby-2.3.1/gems/capybara-2.15.1/lib/capybara/node/matchers.rb:617:in `block in assert_text'
```

Repository to reproduce with more verbose description - https://github.com/sd-kin/poltergeist_bug/tree/master

P.S. Sorry for my english

**Comment by twalpole** [comment]
PhantomJS 2.1.1 only supports up to ES5 - therefore it doesn’t support arrow functions. Either try the PhantomJS 2.5 beta or transpile your code to ES5
