### ISSUE TITLE
Capybara::Poltergeist::StatusFailError: failed to reach server (but manually I can connect perfectly)

### ISSUE THREAD

**Issue by jmuheim** [teampoltergeist/poltergeist#936]
Hello

I'm just upgrading a Rails 5 app to Rails 6. Running the specs, I see that all JS-enabled specs fail with the following:

```
  1) Autocomplete keyboard interaction up options visible moves selection up
     Failure/Error: visit new_page_path
     
     Capybara::Poltergeist::StatusFailError:
       Request to 'http://127.0.0.1:50193/en/pages/new' failed to reach server, check DNS and/or server status - Timed out with no open resource requests
     # /Users/josh/.rvm/gems/ruby-2.6.3@base/gems/poltergeist-1.18.1/lib/capybara/poltergeist/browser.rb:396:in `command'
     # /Users/josh/.rvm/gems/ruby-2.6.3@base/gems/poltergeist-1.18.1/lib/capybara/poltergeist/browser.rb:39:in `visit'
     # /Users/josh/.rvm/gems/ruby-2.6.3@base/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:100:in `visit'
     # /Users/josh/.rvm/gems/ruby-2.6.3@base/gems/capybara-3.33.0/lib/capybara/session.rb:278:in `visit'

etc.
```

This is very strange, because when manually connecting to `http://127.0.0.1:50193/en/pages/new` (while the spec is still running), I can perfectly connect to this address. I have no idea what's going on and how to debug this problem.

Thank you for any hint.

**Comment by twalpole** [comment]
Poltergeist went EOL quite some time ago due to the library it depends on only replicating a browser from 8+ years ago. It’s time to move to a newer driver
